<?php

namespace oGooseBundle\Repository;

/**
 * ProjectauthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectauthorRepository extends \Doctrine\ORM\EntityRepository
{
}
