<?php

namespace oGooseBundle\Repository;

/**
 * ProjecttypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjecttypeRepository extends \Doctrine\ORM\EntityRepository
{
}
